### ISSUE TITLE
Hello. Problem with dfu convert. Which version use qt python an gcc arm. On windows.

### ISSUE THREAD

**Issue by Florbekinaev** [esaulenka/SCan_fw#2]

**Comment by esaulenka** [comment]
sorry, I forgot to answer.

to build it, you need:
- any modern Qt Creator (I have tested it with versions which come with Qt 5.x and 6.x) with Qbs build system
- OR modern CMake. I did several CMake presets to run make variants for all supported boards.
- any gcc-arm-none-eabi from arm.com. Tested with versions 9, 10, 11
- python2.7 or 3 with `intelhex` package installed. You can build everything without it, it is used just to make DFU image to painless update.
