### ISSUE TITLE
Car bus analyzer protocol?

### ISSUE THREAD

**Issue by asror110Isajonov** [esaulenka/SCan_fw#3]
Is it compatible with Russian Car bus analyzer. 
How to migrate other mcu instead of stm32f107?

**Comment by esaulenka** [comment]
Yes, it is. I tested it with 0.7.21 version.
Latest versions have some changes, and I did not modifications for it yet. 

To use other MCU (not 105 or 107) you need some modifications in low-level code. I dont have answer for a this question, it is too general.

**Comment by asror110Isajonov** [comment]
Do you have this version? If you do.Can you share with me?

**Comment by asror110Isajonov** [comment]
> Yes, it is. I tested it with 0.7.21 version. Latest versions have some changes, and I did not modifications for it yet.
> 
> To use other MCU (not 105 or 107) you need some modifications in low-level code. I dont have answer for a this question, it is too general.

Do you have this version? If you do.Can you share with me?
